title: PoLet500
author:
  name: Polemiche Letterarie del Cinquecento
  email: 'polet500@nuovorinascimento.org'
blog:
  route: '/testi/'
metadata:
    title: 'PoLet500 - Polemiche Letterarie del 500'
    description: 'PoLet500 è un progetto in costruzione di schedatura telematica di polemiche letterarie del Cinquecento italiano'
    headline: 'Con la partnership del Dipartimento di lingua e letteratura italiana, Facolta di Studi Umanistici e Sociali, Università di Spalato'
taxonomies: [category,tag,month,char,author,chronology]
redirects:
    /changelog: /testi/the-urban-jungle
routes:
    /something/else: /testi/focus-and-blur
    /another/one/(.*): /testi/$1

